use super::{Instruction, InstructionType, MemoryAdressingMode};

pub(crate) const INSTRUCTION_SET: [Instruction; 255] = [
    instruction!(
        "BRK",
        0x0,
        1,
        7,
        InstructionType::BRK,
        MemoryAdressingMode::Implied,
        false
    ),
    instruction!(
        "ORA",
        0x1,
        2,
        6,
        InstructionType::ORA,
        MemoryAdressingMode::IndirectX,
        false
    ),
    instruction!(
        "NotImplemented",
        0x2,
        0,
        0,
        InstructionType::NotImplemented,
        MemoryAdressingMode::Immediate,
        false
    ),
    instruction!(
        "NotImplemented",
        0x3,
        0,
        0,
        InstructionType::NotImplemented,
        MemoryAdressingMode::Immediate,
        false
    ),
    instruction!(
        "NotImplemented",
        0x4,
        0,
        0,
        InstructionType::NotImplemented,
        MemoryAdressingMode::Immediate,
        false
    ),
    instruction!(
        "ORA",
        0x5,
        2,
        3,
        InstructionType::ORA,
        MemoryAdressingMode::ZeroPage,
        false
    ),
    instruction!(
        "ASL",
        0x6,
        2,
        5,
        InstructionType::ASL,
        MemoryAdressingMode::ZeroPage,
        false
    ),
    instruction!(
        "NotImplemented",
        0x7,
        0,
        0,
        InstructionType::NotImplemented,
        MemoryAdressingMode::Immediate,
        false
    ),
    instruction!(
        "PHP",
        0x8,
        1,
        3,
        InstructionType::PHP,
        MemoryAdressingMode::Implied,
        false
    ),
    instruction!(
        "ORA",
        0x9,
        2,
        2,
        InstructionType::ORA,
        MemoryAdressingMode::Immediate,
        false
    ),
    instruction!(
        "ASL",
        0xa,
        1,
        2,
        InstructionType::ASL,
        MemoryAdressingMode::Accumulator,
        false
    ),
    instruction!(
        "NotImplemented",
        0xb,
        0,
        0,
        InstructionType::NotImplemented,
        MemoryAdressingMode::Immediate,
        false
    ),
    instruction!(
        "NotImplemented",
        0xc,
        0,
        0,
        InstructionType::NotImplemented,
        MemoryAdressingMode::Immediate,
        false
    ),
    instruction!(
        "ORA",
        0xd,
        3,
        4,
        InstructionType::ORA,
        MemoryAdressingMode::Absolute,
        false
    ),
    instruction!(
        "ASL",
        0xe,
        3,
        6,
        InstructionType::ASL,
        MemoryAdressingMode::Absolute,
        false
    ),
    instruction!(
        "NotImplemented",
        0xf,
        0,
        0,
        InstructionType::NotImplemented,
        MemoryAdressingMode::Immediate,
        false
    ),
    instruction!(
        "BPL",
        0x10,
        2,
        2,
        InstructionType::BPL,
        MemoryAdressingMode::Relative,
        true
    ),
    instruction!(
        "ORA",
        0x11,
        2,
        5,
        InstructionType::ORA,
        MemoryAdressingMode::IndirectY,
        true
    ),
    instruction!(
        "NotImplemented",
        0x12,
        0,
        0,
        InstructionType::NotImplemented,
        MemoryAdressingMode::Immediate,
        false
    ),
    instruction!(
        "NotImplemented",
        0x13,
        0,
        0,
        InstructionType::NotImplemented,
        MemoryAdressingMode::Immediate,
        false
    ),
    instruction!(
        "NotImplemented",
        0x14,
        0,
        0,
        InstructionType::NotImplemented,
        MemoryAdressingMode::Immediate,
        false
    ),
    instruction!(
        "ORA",
        0x15,
        2,
        4,
        InstructionType::ORA,
        MemoryAdressingMode::ZeroPageX,
        false
    ),
    instruction!(
        "ASL",
        0x16,
        2,
        6,
        InstructionType::ASL,
        MemoryAdressingMode::ZeroPageX,
        false
    ),
    instruction!(
        "NotImplemented",
        0x17,
        0,
        0,
        InstructionType::NotImplemented,
        MemoryAdressingMode::Immediate,
        false
    ),
    instruction!(
        "CLC",
        0x18,
        1,
        2,
        InstructionType::CLC,
        MemoryAdressingMode::Implied,
        false
    ),
    instruction!(
        "ORA",
        0x19,
        3,
        4,
        InstructionType::ORA,
        MemoryAdressingMode::AbsoluteY,
        true
    ),
    instruction!(
        "NotImplemented",
        0x1a,
        0,
        0,
        InstructionType::NotImplemented,
        MemoryAdressingMode::Immediate,
        false
    ),
    instruction!(
        "NotImplemented",
        0x1b,
        0,
        0,
        InstructionType::NotImplemented,
        MemoryAdressingMode::Immediate,
        false
    ),
    instruction!(
        "NotImplemented",
        0x1c,
        0,
        0,
        InstructionType::NotImplemented,
        MemoryAdressingMode::Immediate,
        false
    ),
    instruction!(
        "ORA",
        0x1d,
        3,
        4,
        InstructionType::ORA,
        MemoryAdressingMode::AbsoluteX,
        true
    ),
    instruction!(
        "ASL",
        0x1e,
        3,
        7,
        InstructionType::ASL,
        MemoryAdressingMode::AbsoluteX,
        false
    ),
    instruction!(
        "NotImplemented",
        0x1f,
        0,
        0,
        InstructionType::NotImplemented,
        MemoryAdressingMode::Immediate,
        false
    ),
    instruction!(
        "JSR",
        0x20,
        3,
        6,
        InstructionType::JSR,
        MemoryAdressingMode::Absolute,
        false
    ),
    instruction!(
        "AND",
        0x21,
        2,
        6,
        InstructionType::AND,
        MemoryAdressingMode::IndirectX,
        false
    ),
    instruction!(
        "NotImplemented",
        0x22,
        0,
        0,
        InstructionType::NotImplemented,
        MemoryAdressingMode::Immediate,
        false
    ),
    instruction!(
        "NotImplemented",
        0x23,
        0,
        0,
        InstructionType::NotImplemented,
        MemoryAdressingMode::Immediate,
        false
    ),
    instruction!(
        "BIT",
        0x24,
        2,
        3,
        InstructionType::BIT,
        MemoryAdressingMode::ZeroPage,
        false
    ),
    instruction!(
        "AND",
        0x25,
        2,
        3,
        InstructionType::AND,
        MemoryAdressingMode::ZeroPage,
        false
    ),
    instruction!(
        "ROL",
        0x26,
        2,
        5,
        InstructionType::ROL,
        MemoryAdressingMode::ZeroPage,
        false
    ),
    instruction!(
        "NotImplemented",
        0x27,
        0,
        0,
        InstructionType::NotImplemented,
        MemoryAdressingMode::Immediate,
        false
    ),
    instruction!(
        "PLP",
        0x28,
        1,
        4,
        InstructionType::PLP,
        MemoryAdressingMode::Implied,
        false
    ),
    instruction!(
        "AND",
        0x29,
        2,
        2,
        InstructionType::AND,
        MemoryAdressingMode::Immediate,
        false
    ),
    instruction!(
        "ROL",
        0x2a,
        1,
        2,
        InstructionType::ROL,
        MemoryAdressingMode::Accumulator,
        false
    ),
    instruction!(
        "NotImplemented",
        0x2b,
        0,
        0,
        InstructionType::NotImplemented,
        MemoryAdressingMode::Immediate,
        false
    ),
    instruction!(
        "BIT",
        0x2c,
        3,
        4,
        InstructionType::BIT,
        MemoryAdressingMode::Absolute,
        false
    ),
    instruction!(
        "AND",
        0x2d,
        3,
        4,
        InstructionType::AND,
        MemoryAdressingMode::Absolute,
        false
    ),
    instruction!(
        "ROL",
        0x2e,
        3,
        6,
        InstructionType::ROL,
        MemoryAdressingMode::Absolute,
        false
    ),
    instruction!(
        "NotImplemented",
        0x2f,
        0,
        0,
        InstructionType::NotImplemented,
        MemoryAdressingMode::Immediate,
        false
    ),
    instruction!(
        "BMI",
        0x30,
        2,
        2,
        InstructionType::BMI,
        MemoryAdressingMode::Relative,
        true
    ),
    instruction!(
        "AND",
        0x31,
        2,
        5,
        InstructionType::AND,
        MemoryAdressingMode::IndirectY,
        true
    ),
    instruction!(
        "NotImplemented",
        0x32,
        0,
        0,
        InstructionType::NotImplemented,
        MemoryAdressingMode::Immediate,
        false
    ),
    instruction!(
        "NotImplemented",
        0x33,
        0,
        0,
        InstructionType::NotImplemented,
        MemoryAdressingMode::Immediate,
        false
    ),
    instruction!(
        "NotImplemented",
        0x34,
        0,
        0,
        InstructionType::NotImplemented,
        MemoryAdressingMode::Immediate,
        false
    ),
    instruction!(
        "AND",
        0x35,
        2,
        4,
        InstructionType::AND,
        MemoryAdressingMode::ZeroPageX,
        false
    ),
    instruction!(
        "ROL",
        0x36,
        2,
        6,
        InstructionType::ROL,
        MemoryAdressingMode::ZeroPageX,
        false
    ),
    instruction!(
        "NotImplemented",
        0x37,
        0,
        0,
        InstructionType::NotImplemented,
        MemoryAdressingMode::Immediate,
        false
    ),
    instruction!(
        "SEC",
        0x38,
        1,
        2,
        InstructionType::SEC,
        MemoryAdressingMode::Implied,
        false
    ),
    instruction!(
        "AND",
        0x39,
        3,
        4,
        InstructionType::AND,
        MemoryAdressingMode::AbsoluteY,
        true
    ),
    instruction!(
        "NotImplemented",
        0x3a,
        0,
        0,
        InstructionType::NotImplemented,
        MemoryAdressingMode::Immediate,
        false
    ),
    instruction!(
        "NotImplemented",
        0x3b,
        0,
        0,
        InstructionType::NotImplemented,
        MemoryAdressingMode::Immediate,
        false
    ),
    instruction!(
        "NotImplemented",
        0x3c,
        0,
        0,
        InstructionType::NotImplemented,
        MemoryAdressingMode::Immediate,
        false
    ),
    instruction!(
        "AND",
        0x3d,
        3,
        4,
        InstructionType::AND,
        MemoryAdressingMode::AbsoluteX,
        true
    ),
    instruction!(
        "ROL",
        0x3e,
        3,
        7,
        InstructionType::ROL,
        MemoryAdressingMode::AbsoluteX,
        false
    ),
    instruction!(
        "NotImplemented",
        0x3f,
        0,
        0,
        InstructionType::NotImplemented,
        MemoryAdressingMode::Immediate,
        false
    ),
    instruction!(
        "RTI",
        0x40,
        1,
        6,
        InstructionType::RTI,
        MemoryAdressingMode::Implied,
        false
    ),
    instruction!(
        "EOR",
        0x41,
        2,
        6,
        InstructionType::EOR,
        MemoryAdressingMode::IndirectX,
        false
    ),
    instruction!(
        "NotImplemented",
        0x42,
        0,
        0,
        InstructionType::NotImplemented,
        MemoryAdressingMode::Immediate,
        false
    ),
    instruction!(
        "NotImplemented",
        0x43,
        0,
        0,
        InstructionType::NotImplemented,
        MemoryAdressingMode::Immediate,
        false
    ),
    instruction!(
        "NotImplemented",
        0x44,
        0,
        0,
        InstructionType::NotImplemented,
        MemoryAdressingMode::Immediate,
        false
    ),
    instruction!(
        "EOR",
        0x45,
        2,
        3,
        InstructionType::EOR,
        MemoryAdressingMode::ZeroPage,
        false
    ),
    instruction!(
        "LSR",
        0x46,
        2,
        5,
        InstructionType::LSR,
        MemoryAdressingMode::ZeroPage,
        false
    ),
    instruction!(
        "NotImplemented",
        0x47,
        0,
        0,
        InstructionType::NotImplemented,
        MemoryAdressingMode::Immediate,
        false
    ),
    instruction!(
        "PHA",
        0x48,
        1,
        3,
        InstructionType::PHA,
        MemoryAdressingMode::Implied,
        false
    ),
    instruction!(
        "EOR",
        0x49,
        2,
        2,
        InstructionType::EOR,
        MemoryAdressingMode::Immediate,
        false
    ),
    instruction!(
        "LSR",
        0x4a,
        1,
        2,
        InstructionType::LSR,
        MemoryAdressingMode::Accumulator,
        false
    ),
    instruction!(
        "NotImplemented",
        0x4b,
        0,
        0,
        InstructionType::NotImplemented,
        MemoryAdressingMode::Immediate,
        false
    ),
    instruction!(
        "JMP",
        0x4c,
        3,
        3,
        InstructionType::JMP,
        MemoryAdressingMode::Absolute,
        false
    ),
    instruction!(
        "EOR",
        0x4d,
        3,
        4,
        InstructionType::EOR,
        MemoryAdressingMode::Absolute,
        false
    ),
    instruction!(
        "LSR",
        0x4e,
        3,
        6,
        InstructionType::LSR,
        MemoryAdressingMode::Absolute,
        false
    ),
    instruction!(
        "NotImplemented",
        0x4f,
        0,
        0,
        InstructionType::NotImplemented,
        MemoryAdressingMode::Immediate,
        false
    ),
    instruction!(
        "BVC",
        0x50,
        2,
        2,
        InstructionType::BVC,
        MemoryAdressingMode::Relative,
        true
    ),
    instruction!(
        "EOR",
        0x51,
        2,
        5,
        InstructionType::EOR,
        MemoryAdressingMode::IndirectY,
        true
    ),
    instruction!(
        "NotImplemented",
        0x52,
        0,
        0,
        InstructionType::NotImplemented,
        MemoryAdressingMode::Immediate,
        false
    ),
    instruction!(
        "NotImplemented",
        0x53,
        0,
        0,
        InstructionType::NotImplemented,
        MemoryAdressingMode::Immediate,
        false
    ),
    instruction!(
        "NotImplemented",
        0x54,
        0,
        0,
        InstructionType::NotImplemented,
        MemoryAdressingMode::Immediate,
        false
    ),
    instruction!(
        "EOR",
        0x55,
        2,
        4,
        InstructionType::EOR,
        MemoryAdressingMode::ZeroPageX,
        false
    ),
    instruction!(
        "LSR",
        0x56,
        2,
        6,
        InstructionType::LSR,
        MemoryAdressingMode::ZeroPageX,
        false
    ),
    instruction!(
        "NotImplemented",
        0x57,
        0,
        0,
        InstructionType::NotImplemented,
        MemoryAdressingMode::Immediate,
        false
    ),
    instruction!(
        "CLI",
        0x58,
        1,
        2,
        InstructionType::CLI,
        MemoryAdressingMode::Implied,
        false
    ),
    instruction!(
        "EOR",
        0x59,
        3,
        4,
        InstructionType::EOR,
        MemoryAdressingMode::AbsoluteY,
        true
    ),
    instruction!(
        "NotImplemented",
        0x5a,
        0,
        0,
        InstructionType::NotImplemented,
        MemoryAdressingMode::Immediate,
        false
    ),
    instruction!(
        "NotImplemented",
        0x5b,
        0,
        0,
        InstructionType::NotImplemented,
        MemoryAdressingMode::Immediate,
        false
    ),
    instruction!(
        "NotImplemented",
        0x5c,
        0,
        0,
        InstructionType::NotImplemented,
        MemoryAdressingMode::Immediate,
        false
    ),
    instruction!(
        "EOR",
        0x5d,
        3,
        4,
        InstructionType::EOR,
        MemoryAdressingMode::AbsoluteX,
        true
    ),
    instruction!(
        "LSR",
        0x5e,
        3,
        7,
        InstructionType::LSR,
        MemoryAdressingMode::AbsoluteX,
        false
    ),
    instruction!(
        "NotImplemented",
        0x5f,
        0,
        0,
        InstructionType::NotImplemented,
        MemoryAdressingMode::Immediate,
        false
    ),
    instruction!(
        "RTS",
        0x60,
        1,
        6,
        InstructionType::RTS,
        MemoryAdressingMode::Implied,
        false
    ),
    instruction!(
        "ADC",
        0x61,
        2,
        6,
        InstructionType::ADC,
        MemoryAdressingMode::IndirectX,
        false
    ),
    instruction!(
        "NotImplemented",
        0x62,
        0,
        0,
        InstructionType::NotImplemented,
        MemoryAdressingMode::Immediate,
        false
    ),
    instruction!(
        "NotImplemented",
        0x63,
        0,
        0,
        InstructionType::NotImplemented,
        MemoryAdressingMode::Immediate,
        false
    ),
    instruction!(
        "NotImplemented",
        0x64,
        0,
        0,
        InstructionType::NotImplemented,
        MemoryAdressingMode::Immediate,
        false
    ),
    instruction!(
        "ADC",
        0x65,
        2,
        3,
        InstructionType::ADC,
        MemoryAdressingMode::ZeroPage,
        false
    ),
    instruction!(
        "ROR",
        0x66,
        2,
        5,
        InstructionType::ROR,
        MemoryAdressingMode::ZeroPage,
        false
    ),
    instruction!(
        "NotImplemented",
        0x67,
        0,
        0,
        InstructionType::NotImplemented,
        MemoryAdressingMode::Immediate,
        false
    ),
    instruction!(
        "PLA",
        0x68,
        1,
        4,
        InstructionType::PLA,
        MemoryAdressingMode::Implied,
        false
    ),
    instruction!(
        "ADC",
        0x69,
        2,
        2,
        InstructionType::ADC,
        MemoryAdressingMode::Immediate,
        false
    ),
    instruction!(
        "ROR",
        0x6a,
        1,
        2,
        InstructionType::ROR,
        MemoryAdressingMode::Accumulator,
        false
    ),
    instruction!(
        "NotImplemented",
        0x6b,
        0,
        0,
        InstructionType::NotImplemented,
        MemoryAdressingMode::Immediate,
        false
    ),
    instruction!(
        "JMP",
        0x6c,
        3,
        5,
        InstructionType::JMP,
        MemoryAdressingMode::Indirect,
        false
    ),
    instruction!(
        "ADC",
        0x6d,
        3,
        4,
        InstructionType::ADC,
        MemoryAdressingMode::Absolute,
        false
    ),
    instruction!(
        "ROR",
        0x6e,
        3,
        6,
        InstructionType::ROR,
        MemoryAdressingMode::Absolute,
        false
    ),
    instruction!(
        "NotImplemented",
        0x6f,
        0,
        0,
        InstructionType::NotImplemented,
        MemoryAdressingMode::Immediate,
        false
    ),
    instruction!(
        "BVS",
        0x70,
        2,
        2,
        InstructionType::BVS,
        MemoryAdressingMode::Relative,
        true
    ),
    instruction!(
        "ADC",
        0x71,
        2,
        5,
        InstructionType::ADC,
        MemoryAdressingMode::IndirectY,
        true
    ),
    instruction!(
        "NotImplemented",
        0x72,
        0,
        0,
        InstructionType::NotImplemented,
        MemoryAdressingMode::Immediate,
        false
    ),
    instruction!(
        "NotImplemented",
        0x73,
        0,
        0,
        InstructionType::NotImplemented,
        MemoryAdressingMode::Immediate,
        false
    ),
    instruction!(
        "NotImplemented",
        0x74,
        0,
        0,
        InstructionType::NotImplemented,
        MemoryAdressingMode::Immediate,
        false
    ),
    instruction!(
        "ADC",
        0x75,
        2,
        4,
        InstructionType::ADC,
        MemoryAdressingMode::ZeroPageX,
        false
    ),
    instruction!(
        "ROR",
        0x76,
        2,
        6,
        InstructionType::ROR,
        MemoryAdressingMode::ZeroPageX,
        false
    ),
    instruction!(
        "NotImplemented",
        0x77,
        0,
        0,
        InstructionType::NotImplemented,
        MemoryAdressingMode::Immediate,
        false
    ),
    instruction!(
        "SEI",
        0x78,
        1,
        2,
        InstructionType::SEI,
        MemoryAdressingMode::Implied,
        false
    ),
    instruction!(
        "ADC",
        0x79,
        3,
        4,
        InstructionType::ADC,
        MemoryAdressingMode::AbsoluteY,
        true
    ),
    instruction!(
        "NotImplemented",
        0x7a,
        0,
        0,
        InstructionType::NotImplemented,
        MemoryAdressingMode::Immediate,
        false
    ),
    instruction!(
        "NotImplemented",
        0x7b,
        0,
        0,
        InstructionType::NotImplemented,
        MemoryAdressingMode::Immediate,
        false
    ),
    instruction!(
        "NotImplemented",
        0x7c,
        0,
        0,
        InstructionType::NotImplemented,
        MemoryAdressingMode::Immediate,
        false
    ),
    instruction!(
        "ADC",
        0x7d,
        3,
        4,
        InstructionType::ADC,
        MemoryAdressingMode::AbsoluteX,
        true
    ),
    instruction!(
        "ROR",
        0x7e,
        3,
        7,
        InstructionType::ROR,
        MemoryAdressingMode::AbsoluteX,
        false
    ),
    instruction!(
        "NotImplemented",
        0x7f,
        0,
        0,
        InstructionType::NotImplemented,
        MemoryAdressingMode::Immediate,
        false
    ),
    instruction!(
        "NotImplemented",
        0x80,
        0,
        0,
        InstructionType::NotImplemented,
        MemoryAdressingMode::Immediate,
        false
    ),
    instruction!(
        "STA",
        0x81,
        2,
        6,
        InstructionType::STA,
        MemoryAdressingMode::IndirectX,
        false
    ),
    instruction!(
        "NotImplemented",
        0x82,
        0,
        0,
        InstructionType::NotImplemented,
        MemoryAdressingMode::Immediate,
        false
    ),
    instruction!(
        "NotImplemented",
        0x83,
        0,
        0,
        InstructionType::NotImplemented,
        MemoryAdressingMode::Immediate,
        false
    ),
    instruction!(
        "STY",
        0x84,
        2,
        3,
        InstructionType::STY,
        MemoryAdressingMode::ZeroPage,
        false
    ),
    instruction!(
        "STA",
        0x85,
        2,
        3,
        InstructionType::STA,
        MemoryAdressingMode::ZeroPage,
        false
    ),
    instruction!(
        "STX",
        0x86,
        2,
        3,
        InstructionType::STX,
        MemoryAdressingMode::ZeroPage,
        false
    ),
    instruction!(
        "NotImplemented",
        0x87,
        0,
        0,
        InstructionType::NotImplemented,
        MemoryAdressingMode::Immediate,
        false
    ),
    instruction!(
        "DEY",
        0x88,
        1,
        2,
        InstructionType::DEY,
        MemoryAdressingMode::Implied,
        false
    ),
    instruction!(
        "NotImplemented",
        0x89,
        0,
        0,
        InstructionType::NotImplemented,
        MemoryAdressingMode::Immediate,
        false
    ),
    instruction!(
        "TXA",
        0x8a,
        1,
        2,
        InstructionType::TXA,
        MemoryAdressingMode::Implied,
        false
    ),
    instruction!(
        "NotImplemented",
        0x8b,
        0,
        0,
        InstructionType::NotImplemented,
        MemoryAdressingMode::Immediate,
        false
    ),
    instruction!(
        "STY",
        0x8c,
        3,
        4,
        InstructionType::STY,
        MemoryAdressingMode::Absolute,
        false
    ),
    instruction!(
        "STA",
        0x8d,
        3,
        4,
        InstructionType::STA,
        MemoryAdressingMode::Absolute,
        false
    ),
    instruction!(
        "STX",
        0x8e,
        3,
        4,
        InstructionType::STX,
        MemoryAdressingMode::Absolute,
        false
    ),
    instruction!(
        "NotImplemented",
        0x8f,
        0,
        0,
        InstructionType::NotImplemented,
        MemoryAdressingMode::Immediate,
        false
    ),
    instruction!(
        "BCC",
        0x90,
        2,
        2,
        InstructionType::BCC,
        MemoryAdressingMode::Relative,
        true
    ),
    instruction!(
        "STA",
        0x91,
        2,
        6,
        InstructionType::STA,
        MemoryAdressingMode::IndirectY,
        false
    ),
    instruction!(
        "NotImplemented",
        0x92,
        0,
        0,
        InstructionType::NotImplemented,
        MemoryAdressingMode::Immediate,
        false
    ),
    instruction!(
        "NotImplemented",
        0x93,
        0,
        0,
        InstructionType::NotImplemented,
        MemoryAdressingMode::Immediate,
        false
    ),
    instruction!(
        "STY",
        0x94,
        2,
        4,
        InstructionType::STY,
        MemoryAdressingMode::ZeroPageX,
        false
    ),
    instruction!(
        "STA",
        0x95,
        2,
        4,
        InstructionType::STA,
        MemoryAdressingMode::ZeroPageX,
        false
    ),
    instruction!(
        "STX",
        0x96,
        2,
        4,
        InstructionType::STX,
        MemoryAdressingMode::ZeroPageY,
        false
    ),
    instruction!(
        "NotImplemented",
        0x97,
        0,
        0,
        InstructionType::NotImplemented,
        MemoryAdressingMode::Immediate,
        false
    ),
    instruction!(
        "TYA",
        0x98,
        1,
        2,
        InstructionType::TYA,
        MemoryAdressingMode::Implied,
        false
    ),
    instruction!(
        "STA",
        0x99,
        3,
        5,
        InstructionType::STA,
        MemoryAdressingMode::AbsoluteY,
        false
    ),
    instruction!(
        "TXS",
        0x9a,
        1,
        2,
        InstructionType::TXS,
        MemoryAdressingMode::Implied,
        false
    ),
    instruction!(
        "NotImplemented",
        0x9b,
        0,
        0,
        InstructionType::NotImplemented,
        MemoryAdressingMode::Immediate,
        false
    ),
    instruction!(
        "NotImplemented",
        0x9c,
        0,
        0,
        InstructionType::NotImplemented,
        MemoryAdressingMode::Immediate,
        false
    ),
    instruction!(
        "STA",
        0x9d,
        3,
        5,
        InstructionType::STA,
        MemoryAdressingMode::AbsoluteX,
        false
    ),
    instruction!(
        "NotImplemented",
        0x9e,
        0,
        0,
        InstructionType::NotImplemented,
        MemoryAdressingMode::Immediate,
        false
    ),
    instruction!(
        "NotImplemented",
        0x9f,
        0,
        0,
        InstructionType::NotImplemented,
        MemoryAdressingMode::Immediate,
        false
    ),
    instruction!(
        "LDY",
        0xa0,
        2,
        2,
        InstructionType::LDY,
        MemoryAdressingMode::Immediate,
        false
    ),
    instruction!(
        "LDA",
        0xa1,
        2,
        6,
        InstructionType::LDA,
        MemoryAdressingMode::IndirectX,
        false
    ),
    instruction!(
        "LDX",
        0xa2,
        2,
        2,
        InstructionType::LDX,
        MemoryAdressingMode::Immediate,
        false
    ),
    instruction!(
        "NotImplemented",
        0xa3,
        0,
        0,
        InstructionType::NotImplemented,
        MemoryAdressingMode::Immediate,
        false
    ),
    instruction!(
        "LDY",
        0xa4,
        2,
        3,
        InstructionType::LDY,
        MemoryAdressingMode::ZeroPage,
        false
    ),
    instruction!(
        "LDA",
        0xa5,
        2,
        3,
        InstructionType::LDA,
        MemoryAdressingMode::ZeroPage,
        false
    ),
    instruction!(
        "LDX",
        0xa6,
        2,
        3,
        InstructionType::LDX,
        MemoryAdressingMode::ZeroPage,
        false
    ),
    instruction!(
        "NotImplemented",
        0xa7,
        0,
        0,
        InstructionType::NotImplemented,
        MemoryAdressingMode::Immediate,
        false
    ),
    instruction!(
        "TAY",
        0xa8,
        1,
        2,
        InstructionType::TAY,
        MemoryAdressingMode::Implied,
        false
    ),
    instruction!(
        "LDA",
        0xa9,
        2,
        2,
        InstructionType::LDA,
        MemoryAdressingMode::Immediate,
        false
    ),
    instruction!(
        "TAX",
        0xaa,
        1,
        2,
        InstructionType::TAX,
        MemoryAdressingMode::Implied,
        false
    ),
    instruction!(
        "NotImplemented",
        0xab,
        0,
        0,
        InstructionType::NotImplemented,
        MemoryAdressingMode::Immediate,
        false
    ),
    instruction!(
        "LDY",
        0xac,
        3,
        4,
        InstructionType::LDY,
        MemoryAdressingMode::Absolute,
        false
    ),
    instruction!(
        "LDA",
        0xad,
        3,
        4,
        InstructionType::LDA,
        MemoryAdressingMode::Absolute,
        false
    ),
    instruction!(
        "LDX",
        0xae,
        3,
        4,
        InstructionType::LDX,
        MemoryAdressingMode::Absolute,
        false
    ),
    instruction!(
        "NotImplemented",
        0xaf,
        0,
        0,
        InstructionType::NotImplemented,
        MemoryAdressingMode::Immediate,
        false
    ),
    instruction!(
        "BCS",
        0xb0,
        2,
        2,
        InstructionType::BCS,
        MemoryAdressingMode::Relative,
        true
    ),
    instruction!(
        "LDA",
        0xb1,
        2,
        5,
        InstructionType::LDA,
        MemoryAdressingMode::IndirectY,
        true
    ),
    instruction!(
        "NotImplemented",
        0xb2,
        0,
        0,
        InstructionType::NotImplemented,
        MemoryAdressingMode::Immediate,
        false
    ),
    instruction!(
        "NotImplemented",
        0xb3,
        0,
        0,
        InstructionType::NotImplemented,
        MemoryAdressingMode::Immediate,
        false
    ),
    instruction!(
        "LDY",
        0xb4,
        2,
        4,
        InstructionType::LDY,
        MemoryAdressingMode::ZeroPageX,
        false
    ),
    instruction!(
        "LDA",
        0xb5,
        2,
        4,
        InstructionType::LDA,
        MemoryAdressingMode::ZeroPageX,
        false
    ),
    instruction!(
        "LDX",
        0xb6,
        2,
        4,
        InstructionType::LDX,
        MemoryAdressingMode::ZeroPageY,
        false
    ),
    instruction!(
        "NotImplemented",
        0xb7,
        0,
        0,
        InstructionType::NotImplemented,
        MemoryAdressingMode::Immediate,
        false
    ),
    instruction!(
        "CLV",
        0xb8,
        1,
        2,
        InstructionType::CLV,
        MemoryAdressingMode::Implied,
        false
    ),
    instruction!(
        "LDA",
        0xb9,
        3,
        4,
        InstructionType::LDA,
        MemoryAdressingMode::AbsoluteY,
        true
    ),
    instruction!(
        "TSX",
        0xba,
        1,
        2,
        InstructionType::TSX,
        MemoryAdressingMode::Implied,
        false
    ),
    instruction!(
        "NotImplemented",
        0xbb,
        0,
        0,
        InstructionType::NotImplemented,
        MemoryAdressingMode::Immediate,
        false
    ),
    instruction!(
        "LDY",
        0xbc,
        3,
        4,
        InstructionType::LDY,
        MemoryAdressingMode::AbsoluteX,
        true
    ),
    instruction!(
        "LDA",
        0xbd,
        3,
        4,
        InstructionType::LDA,
        MemoryAdressingMode::AbsoluteX,
        true
    ),
    instruction!(
        "LDX",
        0xbe,
        3,
        4,
        InstructionType::LDX,
        MemoryAdressingMode::AbsoluteY,
        true
    ),
    instruction!(
        "NotImplemented",
        0xbf,
        0,
        0,
        InstructionType::NotImplemented,
        MemoryAdressingMode::Immediate,
        false
    ),
    instruction!(
        "CPY",
        0xc0,
        2,
        2,
        InstructionType::CPY,
        MemoryAdressingMode::Immediate,
        false
    ),
    instruction!(
        "CMP",
        0xc1,
        2,
        6,
        InstructionType::CMP,
        MemoryAdressingMode::IndirectX,
        false
    ),
    instruction!(
        "NotImplemented",
        0xc2,
        0,
        0,
        InstructionType::NotImplemented,
        MemoryAdressingMode::Immediate,
        false
    ),
    instruction!(
        "NotImplemented",
        0xc3,
        0,
        0,
        InstructionType::NotImplemented,
        MemoryAdressingMode::Immediate,
        false
    ),
    instruction!(
        "CPY",
        0xc4,
        2,
        3,
        InstructionType::CPY,
        MemoryAdressingMode::ZeroPage,
        false
    ),
    instruction!(
        "CMP",
        0xc5,
        2,
        3,
        InstructionType::CMP,
        MemoryAdressingMode::ZeroPage,
        false
    ),
    instruction!(
        "DEC",
        0xc6,
        2,
        5,
        InstructionType::DEC,
        MemoryAdressingMode::ZeroPage,
        false
    ),
    instruction!(
        "NotImplemented",
        0xc7,
        0,
        0,
        InstructionType::NotImplemented,
        MemoryAdressingMode::Immediate,
        false
    ),
    instruction!(
        "INY",
        0xc8,
        1,
        2,
        InstructionType::INY,
        MemoryAdressingMode::Implied,
        false
    ),
    instruction!(
        "CMP",
        0xc9,
        2,
        2,
        InstructionType::CMP,
        MemoryAdressingMode::Immediate,
        false
    ),
    instruction!(
        "DEX",
        0xca,
        1,
        2,
        InstructionType::DEX,
        MemoryAdressingMode::Implied,
        false
    ),
    instruction!(
        "NotImplemented",
        0xcb,
        0,
        0,
        InstructionType::NotImplemented,
        MemoryAdressingMode::Immediate,
        false
    ),
    instruction!(
        "CPY",
        0xcc,
        3,
        4,
        InstructionType::CPY,
        MemoryAdressingMode::Absolute,
        false
    ),
    instruction!(
        "CMP",
        0xcd,
        3,
        4,
        InstructionType::CMP,
        MemoryAdressingMode::Absolute,
        false
    ),
    instruction!(
        "DEC",
        0xce,
        3,
        6,
        InstructionType::DEC,
        MemoryAdressingMode::Absolute,
        false
    ),
    instruction!(
        "NotImplemented",
        0xcf,
        0,
        0,
        InstructionType::NotImplemented,
        MemoryAdressingMode::Immediate,
        false
    ),
    instruction!(
        "BNE",
        0xd0,
        2,
        2,
        InstructionType::BNE,
        MemoryAdressingMode::Relative,
        true
    ),
    instruction!(
        "CMP",
        0xd1,
        2,
        5,
        InstructionType::CMP,
        MemoryAdressingMode::IndirectY,
        true
    ),
    instruction!(
        "NotImplemented",
        0xd2,
        0,
        0,
        InstructionType::NotImplemented,
        MemoryAdressingMode::Immediate,
        false
    ),
    instruction!(
        "NotImplemented",
        0xd3,
        0,
        0,
        InstructionType::NotImplemented,
        MemoryAdressingMode::Immediate,
        false
    ),
    instruction!(
        "NotImplemented",
        0xd4,
        0,
        0,
        InstructionType::NotImplemented,
        MemoryAdressingMode::Immediate,
        false
    ),
    instruction!(
        "CMP",
        0xd5,
        2,
        4,
        InstructionType::CMP,
        MemoryAdressingMode::ZeroPageX,
        false
    ),
    instruction!(
        "DEC",
        0xd6,
        2,
        6,
        InstructionType::DEC,
        MemoryAdressingMode::ZeroPageX,
        false
    ),
    instruction!(
        "NotImplemented",
        0xd7,
        0,
        0,
        InstructionType::NotImplemented,
        MemoryAdressingMode::Immediate,
        false
    ),
    instruction!(
        "CLD",
        0xd8,
        1,
        2,
        InstructionType::CLD,
        MemoryAdressingMode::Implied,
        false
    ),
    instruction!(
        "CMP",
        0xd9,
        3,
        4,
        InstructionType::CMP,
        MemoryAdressingMode::AbsoluteY,
        true
    ),
    instruction!(
        "NotImplemented",
        0xda,
        0,
        0,
        InstructionType::NotImplemented,
        MemoryAdressingMode::Immediate,
        false
    ),
    instruction!(
        "NotImplemented",
        0xdb,
        0,
        0,
        InstructionType::NotImplemented,
        MemoryAdressingMode::Immediate,
        false
    ),
    instruction!(
        "NotImplemented",
        0xdc,
        0,
        0,
        InstructionType::NotImplemented,
        MemoryAdressingMode::Immediate,
        false
    ),
    instruction!(
        "CMP",
        0xdd,
        3,
        4,
        InstructionType::CMP,
        MemoryAdressingMode::AbsoluteX,
        true
    ),
    instruction!(
        "DEC",
        0xde,
        3,
        7,
        InstructionType::DEC,
        MemoryAdressingMode::AbsoluteX,
        false
    ),
    instruction!(
        "NotImplemented",
        0xdf,
        0,
        0,
        InstructionType::NotImplemented,
        MemoryAdressingMode::Immediate,
        false
    ),
    instruction!(
        "CPX",
        0xe0,
        2,
        2,
        InstructionType::CPX,
        MemoryAdressingMode::Immediate,
        false
    ),
    instruction!(
        "SBC",
        0xe1,
        2,
        6,
        InstructionType::SBC,
        MemoryAdressingMode::IndirectX,
        false
    ),
    instruction!(
        "NotImplemented",
        0xe2,
        0,
        0,
        InstructionType::NotImplemented,
        MemoryAdressingMode::Immediate,
        false
    ),
    instruction!(
        "NotImplemented",
        0xe3,
        0,
        0,
        InstructionType::NotImplemented,
        MemoryAdressingMode::Immediate,
        false
    ),
    instruction!(
        "CPX",
        0xe4,
        2,
        3,
        InstructionType::CPX,
        MemoryAdressingMode::ZeroPage,
        false
    ),
    instruction!(
        "SBC",
        0xe5,
        2,
        3,
        InstructionType::SBC,
        MemoryAdressingMode::ZeroPage,
        false
    ),
    instruction!(
        "INC",
        0xe6,
        2,
        5,
        InstructionType::INC,
        MemoryAdressingMode::ZeroPage,
        false
    ),
    instruction!(
        "NotImplemented",
        0xe7,
        0,
        0,
        InstructionType::NotImplemented,
        MemoryAdressingMode::Immediate,
        false
    ),
    instruction!(
        "INX",
        0xe8,
        1,
        2,
        InstructionType::INX,
        MemoryAdressingMode::Implied,
        false
    ),
    instruction!(
        "SBC",
        0xe9,
        2,
        2,
        InstructionType::SBC,
        MemoryAdressingMode::Immediate,
        false
    ),
    instruction!(
        "NOP",
        0xea,
        1,
        2,
        InstructionType::NOP,
        MemoryAdressingMode::Implied,
        false
    ),
    instruction!(
        "NotImplemented",
        0xeb,
        0,
        0,
        InstructionType::NotImplemented,
        MemoryAdressingMode::Immediate,
        false
    ),
    instruction!(
        "CPX",
        0xec,
        3,
        4,
        InstructionType::CPX,
        MemoryAdressingMode::Absolute,
        false
    ),
    instruction!(
        "SBC",
        0xed,
        3,
        4,
        InstructionType::SBC,
        MemoryAdressingMode::Absolute,
        false
    ),
    instruction!(
        "INC",
        0xee,
        3,
        6,
        InstructionType::INC,
        MemoryAdressingMode::Absolute,
        false
    ),
    instruction!(
        "NotImplemented",
        0xef,
        0,
        0,
        InstructionType::NotImplemented,
        MemoryAdressingMode::Immediate,
        false
    ),
    instruction!(
        "BEQ",
        0xf0,
        2,
        2,
        InstructionType::BEQ,
        MemoryAdressingMode::Relative,
        true
    ),
    instruction!(
        "SBC",
        0xf1,
        2,
        5,
        InstructionType::SBC,
        MemoryAdressingMode::IndirectY,
        true
    ),
    instruction!(
        "NotImplemented",
        0xf2,
        0,
        0,
        InstructionType::NotImplemented,
        MemoryAdressingMode::Immediate,
        false
    ),
    instruction!(
        "NotImplemented",
        0xf3,
        0,
        0,
        InstructionType::NotImplemented,
        MemoryAdressingMode::Immediate,
        false
    ),
    instruction!(
        "NotImplemented",
        0xf4,
        0,
        0,
        InstructionType::NotImplemented,
        MemoryAdressingMode::Immediate,
        false
    ),
    instruction!(
        "SBC",
        0xf5,
        2,
        4,
        InstructionType::SBC,
        MemoryAdressingMode::ZeroPageX,
        false
    ),
    instruction!(
        "INC",
        0xf6,
        2,
        6,
        InstructionType::INC,
        MemoryAdressingMode::ZeroPageX,
        false
    ),
    instruction!(
        "NotImplemented",
        0xf7,
        0,
        0,
        InstructionType::NotImplemented,
        MemoryAdressingMode::Immediate,
        false
    ),
    instruction!(
        "SED",
        0xf8,
        1,
        2,
        InstructionType::SED,
        MemoryAdressingMode::Implied,
        false
    ),
    instruction!(
        "SBC",
        0xf9,
        3,
        4,
        InstructionType::SBC,
        MemoryAdressingMode::AbsoluteY,
        true
    ),
    instruction!(
        "NotImplemented",
        0xfa,
        0,
        0,
        InstructionType::NotImplemented,
        MemoryAdressingMode::Immediate,
        false
    ),
    instruction!(
        "NotImplemented",
        0xfb,
        0,
        0,
        InstructionType::NotImplemented,
        MemoryAdressingMode::Immediate,
        false
    ),
    instruction!(
        "NotImplemented",
        0xfc,
        0,
        0,
        InstructionType::NotImplemented,
        MemoryAdressingMode::Immediate,
        false
    ),
    instruction!(
        "SBC",
        0xfd,
        3,
        4,
        InstructionType::SBC,
        MemoryAdressingMode::AbsoluteX,
        true
    ),
    instruction!(
        "INC",
        0xfe,
        3,
        7,
        InstructionType::INC,
        MemoryAdressingMode::AbsoluteX,
        false
    ),
];
