name: Rust

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: sudo apt install libsdl2-dev libsdl2-2.0-0 -y && cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
